export enum Screen {
  LOGIN = 'LOGIN',
  VERIFY_IDENTITY = 'VERIFY_IDENTITY',
  FACE_ID_SETUP = 'FACE_ID_SETUP',
  CONFIRM_DATA = 'CONFIRM_DATA',
  CREATE_PASSWORD = 'CREATE_PASSWORD',
  VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS',
  HOME = 'HOME',
  OPERATIONS = 'OPERATIONS',
  FOR_YOU = 'FOR_YOU',
  PROFILE = 'PROFILE',
  PRODUCT_DETAIL = 'PRODUCT_DETAIL',
  TRANSFER_SELECT = 'TRANSFER_SELECT',
  TRANSFER_AMOUNT = 'TRANSFER_AMOUNT',
  TRANSFER_CONFIRM = 'TRANSFER_CONFIRM',
  TRANSFER_SUCCESS = 'TRANSFER_SUCCESS',
  SERVICES_SELECT = 'SERVICES_SELECT',
  SERVICES_DETAILS = 'SERVICES_DETAILS',
  SERVICES_DEBT = 'SERVICES_DEBT',
  SERVICES_CONFIRM = 'SERVICES_CONFIRM',
  SERVICES_SUCCESS = 'SERVICES_SUCCESS',
  QR_SCAN = 'QR_SCAN',
  QR_AMOUNT = 'QR_AMOUNT',
  QR_CONFIRM = 'QR_CONFIRM',
  QR_SUCCESS = 'QR_SUCCESS',
  EXCHANGE = 'EXCHANGE',
  EXCHANGE_CONFIRM = 'EXCHANGE_CONFIRM',
  EXCHANGE_SUCCESS = 'EXCHANGE_SUCCESS',
  GOALS_LIST = 'GOALS_LIST',
  GOALS_CREATE_CATEGORY = 'GOALS_CREATE_CATEGORY',
  GOALS_CREATE_DETAILS = 'GOALS_CREATE_DETAILS',
  GOALS_SUCCESS = 'GOALS_SUCCESS',
  GOAL_DETAIL = 'GOAL_DETAIL',
  LOAN_SIMULATOR = 'LOAN_SIMULATOR',
  LOAN_REVIEW = 'LOAN_REVIEW',
  LOAN_TERMS = 'LOAN_TERMS',
  LOAN_SUCCESS = 'LOAN_SUCCESS',
  CARD_PAYMENT = 'CARD_PAYMENT',
  CARD_PAYMENT_SELECT = 'CARD_PAYMENT_SELECT',
  CARD_PAYMENT_AMOUNT = 'CARD_PAYMENT_AMOUNT',
  CARD_PAYMENT_SOURCE = 'CARD_PAYMENT_SOURCE',
  CARD_PAYMENT_CONFIRM = 'CARD_PAYMENT_CONFIRM',
  CARD_PAYMENT_SUCCESS = 'CARD_PAYMENT_SUCCESS',
  STATEMENT_SELECT_PRODUCT = 'STATEMENT_SELECT_PRODUCT',
  STATEMENT_SELECT_PERIOD = 'STATEMENT_SELECT_PERIOD',
  STATEMENT_DELIVERY_METHOD = 'STATEMENT_DELIVERY_METHOD',
  STATEMENT_SUCCESS = 'STATEMENT_SUCCESS',
  PROFILE_EDIT = 'PROFILE_EDIT',
  PROFILE_SECURITY = 'PROFILE_SECURITY',
  PROFILE_HELP = 'PROFILE_HELP',
  PROFILE_CARD_SETTINGS = 'PROFILE_CARD_SETTINGS',
  PROFILE_LOCATIONS = 'PROFILE_LOCATIONS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  ALL_TRANSACTIONS = 'ALL_TRANSACTIONS',
  TRANSACTION_DETAIL = 'TRANSACTION_DETAIL'
}

export interface User {
  name: string;
  email: string;
  avatar: string;
}

export interface Account {
  id: string;
  name: string;
  number: string;
  balance: number;
  currency: 'PEN' | 'USD';
  type?: 'DEBIT' | 'CREDIT';
  network?: 'VISA' | 'MASTERCARD';
}

export interface Transaction {
  id: string;
  title: string;
  subtitle: string;
  amount: number;
  currency: 'PEN' | 'USD';
  date: string;
  type: 'income' | 'expense';
  icon?: string;
}